runtime: php
env: flex

runtime_config:
- document_root: public

# Ensure we skip ".env", which is only for local development
skip_files:
  - .env

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 100

env_variables:
  # Put production environment variables here.
  APP_DEBUG: true
  APP_ENV: production
  APP_KEY: d5wzgTWWEpL2S9RDUEree/OvnYCEElAxNnsRRzr58PI=
  APP_NAME: "GCP App - CODE"

  LOG_LEVEL: debug

#DB_DATABASE: db_1
#DB_USERNAME: root
#DB_PASSWORD:
#DB_SOCKET: '/cloudsql/cst-323-373723:us-central1:cst-323'
#
#beta_settings:
#  cloud_sql_instances: 'cst-323-373723:us-central1:cst-323'
